### ISSUE TITLE
The module name Refinement conflicts with a new class introduced in Ruby 3.1

### ISSUE THREAD

**Issue by shugo** [square/refinement#71]
We are going to introduce a new class Refinement in Ruby 3.1:

* https://bugs.ruby-lang.org/issues/17429

The name of the module Refinement in this gem conflicts with it.

Could you consider renaming the module?

Or changing `module Refinement` to `class Refinement` would work.
(However, it's confusing.)

**Comment by justinseanmartin** [comment]
Hi! If ruby maintainers need the `Refinement` specific name to become a Ruby built-in, we can find some alternate solution (renaming, changing types) to supporting Ruby 3.x. Thanks for checking with us.

**Comment by shugo** [comment]
Thank you!
